Vagrant.configure("2") do |config|
  config.vm.define "control" do |control|
    control.vm.box = "debian/jessie64"
    control.vm.box_version = "8.11.1"
    control.vm.hostname = "control-machine"
    control.vm.network :private_network, ip: "10.2.0.10"
    control.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "debian/jessie64"
    web01.vm.box_version = "8.11.1"
    web01.vm.hostname = "web01"
    web01.vm.network :private_network, ip: "10.2.0.11"
    web01.vm.provision :shell, path: "bootstrap.sh"
  end
end
