Vagrant.configure("2") do |config|
  config.vm.define "control" do |control|
    control.vm.box = "nexait/centos7"
    control.vm.box_version = "7.6"
    control.vm.hostname = "control-machine"
    control.vm.network :private_network, ip: "10.2.0.10"
    control.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "lb01" do |lb01|
    lb01.vm.box = "nexait/centos7"
    lb01.vm.box_version = "7.6"
    lb01.vm.hostname = "lb01"
    lb01.vm.network :private_network, ip: "10.2.0.11"
    lb01.vm.network "forwarded_port", guest: 80, host: 8000
    lb01.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "nexait/centos7"
    web01.vm.box_version = "7.6"
    web01.vm.hostname = "web01"
    web01.vm.network :private_network, ip: "10.2.0.21"
    web01.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define "web02" do |web02|
    web02.vm.box = "nexait/centos7"
    web02.vm.box_version = "7.6"
    web02.vm.hostname = "web02"
    web02.vm.network :private_network, ip: "10.2.0.22"
    web02.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define "db01" do |db01|
    db01.vm.box = "nexait/centos7"
    db01.vm.box_version = "7.6"
    db01.vm.hostname = "db01"
    db01.vm.network :private_network, ip: "10.2.0.31"
    db01.vm.provision :shell, path: "bootstrap.sh"
  end
end
